const api = require('./api'),
  logger = require('./logger'),
  { emitter, LIGHT_GROUP_STATE_CHANGE } = require('./events'),
  awaitableWrap = require('./awaitableWrap'),
  { getOnState, getOffState } = require('./states');
/** @typedef {{ on: boolean, bri: number }} LightState */

/**
 * A group of lighting devices (e.g., a light fixture or room).
 *
 * @class LightGroup
 */
module.exports = class LightGroup {
  /**
   * Creates an instance of LightGroup.
   * @param {number} groupId The ID of the light group.
   */
  constructor(groupId) {
    this.id = groupId;
  }

  /**
   * Turns the light group on.
   *
   * @param {number} brightness A decimal value from 0 to 1,
   *  representing how bright to set the light.
   * @param {number} transitionSeconds The length of time
   *  in seconds that the transition to the new state should last.
   */
  async on(brightness, transitionSeconds) {
    await this.setState(getOnState(brightness, transitionSeconds));
  }

  /**
   * Turns the light group off.
   *
   * @param {number} transitionSeconds The length of time
   *  in seconds that the transition to the new state should last.
   */
  async off(transitionSeconds) {
    await this.setState(getOffState(transitionSeconds));
  }

  /**
   * Sets the state of the light group.
   *
   * @param {LightState} state A light state object generated by node-hue-api.
   */
  async setState(state) {
    logger.log(`Changing state of light group ${this.id} to ${JSON.stringify(state)}.`);

    try {
      await awaitableWrap(api.setGroupLightState(this.id, state));

      logger.log(`Light group ${this.id} state successfully changed.`);
      emitter.emit(LIGHT_GROUP_STATE_CHANGE, this.id, state);
    }
    catch (error) {
      logger.log(`Error changing state of light group ${this.id}: ${error}`);
    }
  }

  /**
   * Gets the last action applied to the light group.
   *
   * @returns {Promise<LightState>} A light state object from node-hue-api.
   */
  async getState() {
    let lightGroup = await awaitableWrap(api.getGroup(this.id));
    return lightGroup.lastAction;
  }
};
